### PR TITLE
add mycosnptree workflow

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds an additional workflow to enter at just the `CREATE_PHYLOGENY` step. 
- No new parameters were added, but it does make use of `--input` and `--fasta/--ref*` 

- `--input` now becomes a CSV
    - cols: sample,vcf,vcf_idx
        - sample: the sample name
        - vcf: the path to the vcf file produced by haplotypecaller
        - vcf_idx: the path to the vcf index file

- `--fasta/--ref*` still act the same

## Testing
You can use `-entry NFCORE_MYCOSNPTREE` to make use of it.
```
nextflow run main.nf \
    -entry NFCORE_MYCOSNPTREE \
    --input samples.csv \
    --fasta reference.fa
```

Since we are now using the same in `mycosnp.nf` and `mycosnptree.nf`, if it works in one, it should work in the other.

----- 
PREVIOUS NOTES

I tested using the consensus assemblies from `results/combined/consensus`, which are the full 12MBp consensus assemblies. Rapidnj and Fasttree did not like these because understandibly, they are pretty big compared to the SNP only from `vcf-to-fasta`. 

I have had success using IQ-Tree, which automatically ignores non-informative sites.

I wonder if it would be possible to get the SNP only fasta files per sample as well. Another thing that might be useful is the reference genome used in the `vcf-to-fasta` as well.

Let me know your thoughts! Thank you!

### CODE REVIEW

**Comment by mciprianoCDC** [comment]
This could be a good use case to add trimAL to the pipeline. There is not an nf-core modules for it yet, but there is a biocontainer:
https://depot.galaxyproject.org/singularity/trimal%3A1.4.1--h9f5acd7_6

This would be able to easily remove the conserved sites from the multifasta alignment file, allowing the other tree generating programs to be used. I wonder how close the the "vcf" focused approach this would get.

**Comment by rpetit3** [comment]
Great idea! I'll look into add this to nf-core/modules. There should already be a multiple sequence alignment from some of the pan-genome modules.

Thanks for the feed back, I'll update soon

**Comment by rpetit3** [comment]
@mciprianoCDC I played around with Trimal and got it to work. But in order to keep things consistent, I instead added the steps after HAPLOTYPECALLER. 

Now the expected inputs are the VCF and VCF index files. This way things are exactly the same between the two workflows.

What are your thoughts on this approach?

**Comment by rpetit3** [comment]
Example Usage:

tree.csv
```
sample,vcf,vcf_idx
SRR7909249,/home/robert_petit/repos/public_health_bacterial_genomics/temp/nf/results/samples/SRR7909249/variant_calling/haplotypecaller/SRR7909249.g.vcf.gz,/home/robert_petit/repos/public_health_bacterial_genomics/temp/nf/results/samples/SRR7909249/variant_calling/haplotypecaller/SRR7909249.g.vcf.gz.tbi
SRR7909282,/home/robert_petit/repos/public_health_bacterial_genomics/temp/nf/results/samples/SRR7909282/variant_calling/haplotypecaller/SRR7909282.g.vcf.gz,/home/robert_petit/repos/public_health_bacterial_genomics/temp/nf/results/samples/SRR7909282/variant_calling/haplotypecaller/SRR7909282.g.vcf.gz.tbi
```

```
nextflow run ~/repos/mycosnp-nf/main.nf --input tree.csv -profile docker -entry NFCORE_MYCOSNPTREE --ref_dir ../docker/reference/GCA_016772135/ --outdi
r mycosnotree
N E X T F L O W  ~  version 21.10.6
Launching `/home/robert_petit/repos/mycosnp-nf/main.nf` [zen_becquerel] - revision: 2461e18a60


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  CDCgov/mycosnp-nf v1.0dev
------------------------------------------------------
Core Nextflow options
  runName         : zen_becquerel
  containerEngine : docker
  launchDir       : /home/robert_petit/repos/public_health_bacterial_genomics/temp/nf
  workDir         : /home/robert_petit/repos/public_health_bacterial_genomics/temp/nf/work
  projectDir      : /home/robert_petit/repos/mycosnp-nf
  userName        : robert_petit
  profile         : docker
  configFiles     : /home/robert_petit/repos/mycosnp-nf/nextflow.config

Input/output options
  input           : tree.csv
  outdir          : mycosnotree
  publish_dir_mode: symlink

Reference genome options
  ref_dir         : ../docker/reference/GCA_016772135/

Max job request options
  max_cpus        : 4
  max_memory      : 6.GB

Generic options
  tmpdir          : /home/robert_petit/repos/mycosnp-nf/tmp

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use CDCgov/mycosnp-nf for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/CDCgov/mycosnp-nf/blob/master/CITATIONS.md
------------------------------------------------------
unknown recognition error type: groovyjarjarantlr4.v4.runtime.LexerNoViableAltException
executor >  local (16)
[10/534497] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK4_LOCALCOMBINEGVCFS (combined)                    [100%] 1 of 1 ✔
[31/23e38e] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:GATK4_GENOTYPEGVCFS (combined-tree)     [100%] 1 of 1 ✔
[21/cf0296] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:GATK4_VARIANTFILTRATION (combined-tree) [100%] 1 of 1 ✔
[1a/d6948a] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:GATK4_SELECTVARIANTS (combined-tree)    [100%] 1 of 1 ✔
[7d/338326] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:FILTER_GATK_GENOTYPES (combined-tree)   [100%] 1 of 1 ✔
[7e/61769d] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:BCFTOOLS_VIEW_CONVERT (combined-tree)   [100%] 1 of 1 ✔
[f1/d916ae] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:BCFTOOLS_INDEX (combined-tree)          [100%] 1 of 1 ✔
[23/0e7099] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:SPLIT_VCF (combined-tree)               [100%] 1 of 1 ✔
[8a/11ae76] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:VCF_CONSENSUS (combined-tree)           [100%] 1 of 1 ✔
[12/6011fe] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:VCF_TO_FASTA (combined-tree)            [100%] 1 of 1 ✔
[cb/7caa5f] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:GATK_VARIANTS:VCF_QC (vcf-qc)                         [100%] 1 of 1 ✔
[e0/44e7db] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:SEQKIT_REPLACE (combined-tree)                        [100%] 1 of 1 ✔
[48/2e5e2f] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:CREATE_PHYLOGENY:RAPIDNJ (1)                          [100%] 1 of 1 ✔
[34/899aa0] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:CREATE_PHYLOGENY:FASTTREE (1)                         [100%] 1 of 1 ✔
[f9/485f24] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:CUSTOM_DUMPSOFTWAREVERSIONS (1)                       [100%] 1 of 1 ✔
[03/95bcea] process > NFCORE_MYCOSNPTREE:MYCOSNPTREE:MULTIQC                                               [100%] 1 of 1 ✔
-[CDCgov/mycosnp-nf] Pipeline completed successfully-
-[CDCgov/mycosnp-nf] Pipeline completed successfully-
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Completed at: 23-Mar-2022 18:14:02
Duration    : 1m 47s
CPU hours   : (a few seconds)
Succeeded   : 16
```

**Comment by mciprianoCDC** [comment]
I think this approach works best, though I wonder now if it overlaps the functionality we just added in vcf-file branch. I think we get the same output though use a slightly different csv file (the vcf-file is just a list of VCF files, not a csv)

**Comment by rpetit3** [comment]
Yep! Closing in favor of https://github.com/CDCgov/mycosnp-nf/tree/vcf-file

**Pull request closed without merging**
